-- MySQL Script generated by MySQL Workbench
-- Сб 27 мар 2021 10:55:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema IcicleSpy3
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `IcicleSpy3` ;

-- -----------------------------------------------------
-- Schema IcicleSpy3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IcicleSpy3` ;
USE `IcicleSpy3` ;

-- -----------------------------------------------------
-- Table `IcicleSpy3`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IcicleSpy3`.`addresses` ;

CREATE TABLE IF NOT EXISTS `IcicleSpy3`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `coordinates` POINT NOT NULL,
  `country` VARCHAR(64) NOT NULL,
  `region_state` VARCHAR(32) NOT NULL,
  `city` VARCHAR(32) NOT NULL,
  `street` VARCHAR(32) NOT NULL,
  `building` VARCHAR(16) NOT NULL,
  `index` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IcicleSpy3`.`devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IcicleSpy3`.`devices` ;

CREATE TABLE IF NOT EXISTS `IcicleSpy3`.`devices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(32) NOT NULL,
  `addresses_id` INT NOT NULL,
  PRIMARY KEY (`id`, `addresses_id`),
  INDEX `fk_devices_addresses_idx` (`addresses_id` ASC),
  CONSTRAINT `fk_devices_addresses`
    FOREIGN KEY (`addresses_id`)
    REFERENCES `IcicleSpy3`.`addresses` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IcicleSpy3`.`cameras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IcicleSpy3`.`cameras` ;

CREATE TABLE IF NOT EXISTS `IcicleSpy3`.`cameras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(32) NOT NULL,
  `addresses_id` INT NOT NULL,
  `devices_id` INT NOT NULL,
  PRIMARY KEY (`id`, `addresses_id`, `devices_id`),
  INDEX `fk_cameras_addresses1_idx` (`addresses_id` ASC),
  INDEX `fk_cameras_devices1_idx` (`devices_id` ASC),
  CONSTRAINT `fk_cameras_addresses1`
    FOREIGN KEY (`addresses_id`)
    REFERENCES `IcicleSpy3`.`addresses` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cameras_devices1`
    FOREIGN KEY (`devices_id`)
    REFERENCES `IcicleSpy3`.`devices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IcicleSpy3`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IcicleSpy3`.`users` ;

CREATE TABLE IF NOT EXISTS `IcicleSpy3`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(64) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `company` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IcicleSpy3`.`devices_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IcicleSpy3`.`devices_data` ;

CREATE TABLE IF NOT EXISTS `IcicleSpy3`.`devices_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` DATETIME NOT NULL,
  `temperature` FLOAT NOT NULL,
  `air_humidity` FLOAT NOT NULL,
  `count` INT NOT NULL,
  `bbox` VARCHAR(256) NOT NULL,
  `img` LONGBLOB NULL DEFAULT NULL,
  `devices_id` INT NOT NULL,
  `cameras_id` INT NOT NULL,
  PRIMARY KEY (`id`, `devices_id`, `cameras_id`),
  INDEX `fk_devices_data_devices1_idx` (`devices_id` ASC),
  INDEX `fk_devices_data_cameras1_idx` (`cameras_id` ASC),
  CONSTRAINT `fk_devices_data_devices1`
    FOREIGN KEY (`devices_id`)
    REFERENCES `IcicleSpy3`.`devices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_devices_data_cameras1`
    FOREIGN KEY (`cameras_id`)
    REFERENCES `IcicleSpy3`.`cameras` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IcicleSpy3`.`users_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IcicleSpy3`.`users_data` ;

CREATE TABLE IF NOT EXISTS `IcicleSpy3`.`users_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `time` DATETIME NOT NULL,
  `count` INT NOT NULL,
  `bbox` VARCHAR(256) NOT NULL,
  `img` LONGBLOB NULL DEFAULT NULL,
  `coordinates` POINT NULL DEFAULT NULL,
  `devices_id` INT NOT NULL,
  `cameras_id` INT NOT NULL,
  PRIMARY KEY (`id`, `devices_id`, `cameras_id`),
  INDEX `fk_users_data_cameras1_idx` (`cameras_id` ASC),
  INDEX `fk_users_data_devices1_idx` (`devices_id` ASC),
  CONSTRAINT `fk_users_data_cameras1`
    FOREIGN KEY (`cameras_id`)
    REFERENCES `IcicleSpy3`.`cameras` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_data_devices1`
    FOREIGN KEY (`devices_id`)
    REFERENCES `IcicleSpy3`.`devices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
